apiVersion: v1
kind: PersistentVolume
metadata:
  name: oracle-pv
  labels:
    type: oracle
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /data/k8s/oracle-pv
    server: 192.168.159.20