apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-deployment
  labels:
    app: oracle
spec:
  selector:
    matchLabels:
      app: oracle
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oracle
    spec:
      containers:
      - image: wnameless/oracle-xe-11g-r2:latest
        name: oracle
        ports:
        - containerPort: 1521
          name: oracle
        volumeMounts:
        - name: data
          mountPath: /ORCL
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: oracle-pvc
