apiVersion: v1
kind: Service
metadata:
  name: oracle-service
spec:
  type: LoadBalancer
  selector:
    app: oracle
  ports:
    - name: client
      protocol: TCP
      port: 1521
      nodePort: 31521
    